@startuml

'cd "C:\Users\Dad\Python Projects\osspea"
'git pull origin main'

'git add .'
'git commit -m "Updated osspa.plantuml"'
'git push origin main

title Open Source Software (OSS) Project Enterprise Architecture

skinparam Style strict

folder "Inputs" #lightgreen {
    [Requirements and Specifications]
    [Financial Support]
    [Hosting and Infrastructure]
    folder "User Feedback" {
        [Bug Reports]
        [Issue Reports]
        [Feature Requests]
    }
    [Surveys and Polls]
}

folder "People_Roles" {
    folder "Core Development" {
        :Maintainer:
        :Contributor:
        :Reviewer:
    }
    folder "Documentation and Design" {
        :Documenter:
        :Designer:
    }
    folder "Community and Project Management" {
        :Creator:
        :Community Manager:
        :Tester:
        :Release Manager:
        :Security Expert:
        :Translator:
    }
    folder "Users" {
        :End User:
        :Power User:
    }
}
together {
    folder "Processes" {
        folder "Commit" {
            [Developing]
            [Testing Commit]
            [Security Testing]
            [Documenting Commit]
        }
        folder "Pull Request" {
            [Designing]
            [Reviewing]
            [Developing]
            [Testing PR]
        }
        folder "Community Support" {
            [Planning]
            [Documenting]
            [Releasing]
            [Monitoring]
            [Translating]
            [Community Engagement]
            [User Support and Feedback]
        }
        folder "Infrastructure Management" {
            [For Hosted OSS Implementations]
        }
    }

    folder "Tools" {
        folder "Version Control" {
            [GitHub] 
            [Bitbucket] #lightblue
            [Git] #lightblue
        }
        folder "Project Management and Issue Tracking" {
            [Jira]
            [Trello]
            [GitLab] #lightblue
            [OpenProject] #lightblue
            [Redmine] #lightblue
        }
        folder "Code Editors and IDEs" {
            [Visual Studio Code] #lightblue
            [IntelliJ IDEA]
        }
        folder "Code Review" {
            [Review Board] #lightblue
        }
        folder "Documents" {
            [Sphinx] #lightblue
            [MkDocs] #lightblue
            [Jekyll] #lightblue
            [Read the Docs] #lightblue
            [Google Docs]
        }
        folder "Design and UX" {
            [Adobe XD]
            [Sketch]
            [Figma]
            [InVision]
            [GIMP] #lightblue
        }
        folder "Communication and Collaboration" {
            [Slack]
            [Discord] #lightblue
            [Twitter]
            [GitHub Discussions] #lightblue
            [Discourse] #lightblue
        }
        folder "Testing and Quality Assurance" {
            [Selenium] #lightblue
            [PyTest] #lightblue
            [JUnit] #lightblue
            [TestRail]
        }
        folder "Continuous Integration (CI) and Continuous Deployment (CD)" {
            [Jenkins] #lightblue
            [Travis CI] #lightblue
            [CircleCI]
            [GitHub Actions] #lightblue
        }
        folder "Security" {
            [OWASP ZAP] #lightblue
            [Burp Suite]
            [Nessus]
            [Metasploit] #lightblue
            [GNU Privacy Guard] #lightblue
        }
        folder "Localization and Translation" {
            [POEditor]
            [Transifex] #lightblue
            [Crowdin] #lightblue
            [Google Translate]
            [Lokalise]
        }
        folder "Metrics" {
            [CHAOSS] #lightblue
        }
    }
}

folder "Outputs" #lightblue {
    folder "Code" {
        [Source Code]
        [Binaries and Executables]
    }
    folder "Documentation" {
        [Documentation]
        [Release Notes]
        [License Information]
    }
    folder "Quality Assurance" {
        [Issue Tracking and Bug Reports]
        [Test Cases and Test Results]
        [Continuous Integration (CI) Configurations]
    }
    folder "Community" {
        [Community Guidelines]
        [Project Roadmap]
        [Marketing Materials]
        [Localizations and Translations]
    }
}

Inputs --> People_Roles
People_Roles --> Processes
People_Roles --> Tools
Processes --> Outputs
Tools --> Outputs

legend left
|=Color |= Description |
|<#ADD8E6>| Open Source Software Project |
endlegend

@enduml
